spring:
  profiles:
    group:
      local: localDB, jasypt, jpa, aws, oauth, jwt, localRedis
      test: testDB, jasypt, jpa, aws, oauth, jwt, localRedis
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
