cloud:
  aws:
    credentials:
      accessKey: AKIAZ4A6LOLSRM37HM6G
      secretKey: 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
    s3:
      bucket: test-issue-tracker-team5
    region:
      static: ap-northeast-2
    stack:
      auto: false
