spring:
  profiles:
    group:
      local: localDB,jpa,aws,oauth,jwt
      test: localDB,jpa,aws,oauth,jwt
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
