spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Y1y1orCAtY8TuJpiIEN+fyPRhdoIGMOiQbo/oI3c+hjHs91+Wn7J9Qb8AQOz8iATqvN6f+c6Kb5tddUBtDp/AgErdANB9UD6MVe/UzFifz+/u0WfIRXrtmFBmFV09bMh)
    username: ENC(HLCBTLeP6kAnFG6G/GFJxQ==)
    password: ENC(aQ7hLHJ8SXI0/TSSAbdvAym2B81XcMJWLahCcNIZ0VCcAH4qTMM2LhK9O8Jv44s2)
